# Copyright (c) IBM Corporation 2020

- name: test role for provision_software_service
  hosts: cpm
  gather_facts: no
  vars_files:
    - "group_vars/all.yml"
  collections:
    - ibm.ibm_zos_zosmf
  vars:
    - name: instance_info_json_path #will store instance json information globally thru the playbook
  tasks:
    - include_role:
        name: remove_software_instance
      vars:
        instance_info_json_path: "<full-instance-json-file-path>"
