# Copyright (c) IBM Corporation 2020

- name: test role for zmf_cpm_provision_software_service
  hosts: zosmf1 # use to match group_vars/cpm.yml
  gather_facts: no
  collections:
    - ibm.ibm_zos_zosmf
  vars:
    - name: instance_info_json_path #will store instance json information globally thru the playbook
  vars_prompt:
    - name: zmf_user
      prompt: "Enter your zOSMF username"
      private: no

    - name: zmf_password
      prompt: "Enter your zOSMF password"
      private: yes
  tasks:
    - include_role:
        name: zmf_cpm_provision_software_service
      vars:
        cpm_template_name: "sampleTemplate"   # The value for property cpm_template_name which identifies the template (software service) user wants to provision with Cloud Provisioning & Management
        domain_name: "default" # The value for property domain_name which identifies CP&M domain in which specified template is defined
        tenant_name: "default" # The value for optional property tenant_name which identifies CP&M tenant that is associated with the zmf_user that is provisioning the template
        systems_nicknames: "SY1" # The value for optional property systems_nicknames which identifies on which system the software instance will be provisioned

