# Copyright (c) IBM Corporation 2020 

# This sample playbook demonstrates using complete_workflow to complete a z/OS workflow.
# Example:
# ansible-playbook -i hosts sample_role_complete_workflow.yml

- name: sample of completing a z/OS workflow
  hosts: workflow
  gather_facts: no
  collections:
    - ibm.ibm_zos_zosmf
  tasks:
    # create and start a workflow, then check the status
    - include_role:
        name: complete_workflow
      vars:
        force_complete: False
        zos_workflow_name: "ansible_sample_workflow_{{ inventory_hostname }}"
        zos_workflow_file: "/var/zosmf/workflow_def/workflow_sample_automation_steps.xml"
    - debug: var=result