# Copyright (c) IBM Corporation 2020

# This sample playbook demonstrates provisioning CICS region and deploying application into CICS region file system
# Example:
# ansible-playbook -i hosts sample_roles_deploy_cics_application.yml

- name: Sample for provisioning CICS region and deploying application
  hosts: cpm
  gather_facts: no
  collections:
    - ibm.ibm_zos_zosmf
  vars:
    - name: instance_info_json_path #will store instance json information globally thru the playbook
  vars_prompt:
    - name: zmf_user
      prompt: "Enter your zOSMF username"
      private: no

    - name: zmf_password
      prompt: "Enter your zOSMF password"
      private: yes

    - name: application_path_input
      prompt: "Enter your application file full path"
      private: no

  tasks:
    - include_role:
        name: provision_software_service
      vars:
        cpm_template_name: "<template-name>"

#########################################################################################################
#
#   WARNING! to use this role, you need to manually copy ./files/cics_wlp_install_app
#   to collections/roles/ibm/ibm_zos_zosmf/roles to make the role self available to user
#
##########################################################################################################

    - include_role:
        name: cics_wlp_install_app
      vars:
        instance_info_json: "{{lookup('file', instance_info_json_path)}}"
        app_root_uri: "/CloudTestServlet"
        app_file_name: "CloudTestServlet.war"
        application_path: "{{ application_path_input }}"
