# Copyright (c) IBM Corporation 2020 
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

---
- uri:
    url: "{{ file_item['records-url'] }}?mode=text&research={{ job_search_output | urlencode }}&insensitive={{ job_search_output_insensitive }}&maxreturnsize={{ job_search_output_maxreturnsize }}"
    method: GET
    return_content: yes
    headers:
      X-IBM-Target-System: "{{ inventory_hostname }}"
      X-CSRF-ZOSMF-HEADER: "TEST"
    user: "{{ zmf_user }}"
    password: "{{ zmf_password }}"
    client_cert: "{{ zmf_crt }}"
    client_key: "{{ zmf_key }}"
    force_basic_auth: yes
    status_code: "200"
    validate_certs: no
  delegate_to: localhost
  register: record_result
  failed_when: no

- include_tasks: handle_request_error.yml
  vars:
    expect_rcode: 200
    result: "{{ record_result }}"

- set_fact:
    job_matched_contents: "{{ job_matched_contents | combine({ file_item.ddname: record_result.content }) }}"