# Copyright (c) IBM Corporation 2020

# The value for property zmf_host is the hostname of the system on which z/OSMF server is running on.
# The value for property zmf_port is the port number of z/OSMF server.
# The value for property zmf_user is your username of z/OSMF.
# The value for property zmf_password is the password of your username of z/OSMF.

zmf_host: sample.ibm.com
zmf_port: 443
zmf_user: user1
zmf_password: password1

# Client certificate is supported by specifying the location of client certificate and key files on control node via zmf_crt and zmf_key.
# If below variables are specified, then the module and role will use client certificate to login instead of using username/password even those variables are specified.
# zmf_crt:
# zmf_key:

instance_record_dir: "/tmp" # The value for property instance_record_dir identifies the file path in local system where the provision result (in json) will be stored
