# Copyright (c) IBM Corporation 2020

api_polling_retry_count: 50 # The value for property api_polling_retry_count identifies max times of status polling before task fail and exit

api_polling_interval_seconds: 10 # The value for property api_polling_interval_seconds identifies interval in seconds between each api_polling_retry_count polling
