# Copyright (c) IBM Corporation 2020 

# This sample playbook demonstrates using role `zmf_role_complete` to complete a job.
# Example:
# ansible-playbook -i hosts sample_role_job_complete.yml

- name: sample of submitting a job to run on z/OS and check its return code
  hosts: job
  gather_facts: no
  collections:
    - ibm.ibm_zos_zosmf
  vars_prompt:
    - name: zmf_user
      prompt: "Enter your zOSMF username (skip if zmf_crt and zmf_key are supplied)"
      private: no
    - name: zmf_password
      prompt: "Enter your zOSMF password (skip if zmf_crt and zmf_key are supplied)"
      private: yes
  tasks:
    - include_role:
        name: zmf_job_complete
      vars:
        job_jcl_src: "files/job_sample_jcl.jcl"
