# Copyright (c) IBM Corporation 2020

# This sample playbook demonstrates using manage_software_instance to perform a
# specific action on provisioned software instance.
# Example:
# ansible-playbook -i hosts sample_role_cpm_manage_instance.yml

- name: sample of managing software instance
  hosts: cpm # use to match group_vars/cpm.yml
  gather_facts: no
  collections:
    - ibm.ibm_zos_zosmf
  vars_prompt:
    - name: zmf_user
      prompt: "Enter your zOSMF username"
      private: no

    - name: zmf_password
      prompt: "Enter your zOSMF password"
      private: yes
  tasks:
    - include_role:
        name: manage_software_instance
      vars:
        instance_action_name: "<action-name>"
        instance_info_json_path: "<full-instance-json-file-path>"
